# Generated by Django 2.2 on 2020-03-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=500)),
                ('intensity', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('category', models.CharField(choices=[('CA', 'Cardio'), ('ST', 'Strength'), ('EN', 'Endurance'), ('FL', 'Flexibility'), ('ME', 'Meditation'), ('SP', 'Speed')], max_length=2)),
            ],
        ),
    ]
