# Generated by Django 2.2 on 2020-02-23 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='store_pics')),
                ('department', models.CharField(choices=[('S', 'Shoes'), ('C', 'Clothing'), ('T', 'Technology')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItemReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, default='', max_length=280)),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StoreItem')),
            ],
        ),
    ]
