# Generated by Django 2.2 on 2020-02-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200222_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='challenges_completed',
            field=models.ManyToManyField(to='users.FitnessChallenge'),
        ),
    ]
