# Generated by Django 2.2 on 2020-02-23 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20200222_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_text', models.TextField(max_length=300)),
                ('worth', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('challenge_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.CreateModel(
            name='FitnessChallengeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=7, default=0, max_digits=8)),
                ('date_accepted', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2020, 2, 24, 17, 35, 33, 184571))),
                ('fitness_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.FitnessChallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
