# Generated by Django 3.0.4 on 2020-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='category',
            field=models.CharField(choices=[('CA', 'Cardio'), ('ST', 'Strength'), ('FL', 'Flexibility'), ('ME', 'Meditation'), ('SP', 'Speed'), ('GE', 'General')], max_length=2),
        ),
    ]
