# Generated by Django 3.0.4 on 2020-03-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.URLField(default='https://www.allrecipes.com/recipe/132358/easy-garlic-lemon-scallops/?internalSource=popular&referringContentType=Homepage'),
            preserve_default=False,
        ),
    ]
