# Generated by Django 3.0.4 on 2020-03-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='escher_pic.jpg', upload_to='recipe_pics'),
        ),
    ]
