# Generated by Django 3.0.4 on 2020-03-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(default='15 min', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('FR', 'Fruit'), ('VE', 'Vegetables'), ('ME', 'Meat'), ('GR', 'Grains'), ('CA', 'Carbs'), ('DE', 'Dessert')], max_length=2),
        ),
    ]
